# Generated by Django 4.0.1 on 2022-02-02 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='QnA.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QnA.profile')),
            ],
            bases=('QnA.profile',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QnA.profile')),
            ],
            bases=('QnA.profile',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('body', models.TextField(max_length=999)),
                ('likes', models.IntegerField()),
                ('submit_date', models.DateField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QnA.board')),
                ('submitted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='QnA.profile')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QnA.course'),
        ),
        migrations.AddField(
            model_name='board',
            name='viewers',
            field=models.ManyToManyField(to='QnA.Profile'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=999)),
                ('answered_date', models.DateField()),
                ('answered_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='QnA.profile')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QnA.question')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_tutor', to='QnA.tutor'),
        ),
        migrations.AddField(
            model_name='board',
            name='tutors',
            field=models.ManyToManyField(related_name='viewable_by_tutor', to='QnA.Tutor'),
        ),
    ]
