# Generated by Django 4.0.1 on 2022-02-01 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univeristy_id', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=99)),
                ('surname', models.CharField(blank=True, max_length=99)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='QnA.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QnA.profile')),
            ],
            bases=('QnA.profile',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QnA.profile')),
            ],
            bases=('QnA.profile',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('body', models.TextField(max_length=999)),
                ('likes', models.IntegerField()),
                ('submit_date', models.DateField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QnA.board')),
                ('submitted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='QnA.profile')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QnA.course'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=999)),
                ('answered_date', models.DateField()),
                ('answered_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='QnA.profile')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QnA.question')),
            ],
        ),
    ]
