# Generated by Django 4.0.1 on 2022-02-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0003_alter_board_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
