# Generated by Django 4.0.1 on 2022-02-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0004_board_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
